# fzcam_sync configuration file
#
# FPS: frames per second * 100
#   Valid range: 100 ~ 9000 (1.00 ~ 90.00 Hz)
#   Default: 3000 (30.00 Hz)
FPS=2000

# DUTY_CYCLE: PWM duty cycle in percent
#   Valid range: 1 ~ 99
#   Default: 10
DUTY_CYCLE=10
